name: continuous-integration
on: push

defaults:
  run:
    shell: pwsh

jobs:
  test:
    runs-on: ${{matrix.platform}}
    strategy:
      matrix:
        platform: [ubuntu-latest, windows-latest]
    steps:
      - name: Fetch sources
        uses: actions/checkout@v5
      - name: Set up Lix
        uses: lix-pm/setup-lix@master
      - name: Set up HashLink
        uses: cedx/setup-hashlink@v7
        with:
          version: latest
      - name: Install dependencies
        run: lix download
      - name: Run tests
        run: haxe test.hxml
