name: continuous-integration
on: push

jobs:
  test:
    runs-on: ${{matrix.platform}}
    strategy:
      matrix:
        platform: [macos-latest, ubuntu-latest, windows-latest]
    steps:
      - name: Fetch sources
        uses: actions/checkout@v4
      - name: Set up Lix
        uses: lix-pm/setup-lix@master
      - name: Set up HashLink
        uses: cedx/setup-hashlink@v4
        with:
          version: latest
      - name: Cache dependencies
        uses: actions/cache@v4
        with:
          path: |
            ~/haxe
            ~/AppData/Roaming/haxe
          key: haxe-${{runner.os}}-lix-${{hashFiles('.haxerc', 'haxe_libraries/*.hxml')}}
          restore-keys: haxe-${{runner.os}}-lix-
      - name: Install dependencies
        run: lix download
      - name: Run tests
        run: haxe test.hxml
