name: Setup HashLink VM
description: Set up your GitHub Actions workflow with a specific version of the HashLink VM.
author: Cédric Belin

branding:
  color: purple
  icon: download

inputs:
  version:
    description: The version constraint of the HashLink VM.
    default: latest
    required: false

runs:
  using: node16
  main: bin/setup_hashlink.js
