author: Cédric Belin
name: Setup HashLink VM
description: Set up your GitHub Actions workflow with a specific version of the HashLink VM.

branding:
  color: purple
  icon: download

inputs:
  version:
    description: The version constraint of the HashLink VM.
    default: latest
    required: false

runs:
  using: composite
  steps:
    - run: Add-Content $Env:GITHUB_PATH ${{github.action_path}}
      shell: pwsh
    - run: start.ps1
      shell: pwsh
      env:
        SETUP_HASHLINK_VERSION: ${{inputs.version}}
